name: Node.js CSE Scraper

on:
  schedule:
    # বাংলাদেশ সময় দুপুর ৩:১৫ মিনিটে (রবি থেকে বৃহস্পতিবার) স্বয়ংক্রিয়ভাবে চলবে
    - cron: '15 9 * * 1-5'
  workflow_dispatch: # ফোন থেকে ম্যানুয়ালি রান করার অপশন

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      # গিটহাবের অ্যাকশনগুলোকে জোরপূর্বক Node 24-এ রান করানোর কমান্ড
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # এখানে আমরা ২৪ করে দিলাম

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: node scraper.js
